sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 101.35.87.146
    port: 3306
    database: sky_take_out
    username: root
    password: rainying0411


  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tGJKWuBifboPQrMQFze
    access-key-secret: PghR2lcWRjJI4UupdqLtPVXCIz9INS
    bucket-name: linkeda

  wechat:
    appid: wx6992d543f32f411a
    secret: 6f74e65fad7d71d48947744815bfa942